### PR TITLE
NanoDeviceBase.CLRVersion made virtual

### PR DESCRIPTION
**Pull request by frobijn**
## Description

* NanoDeviceBase.CLRVersion made virtual

## Motivation and Context

Missed this one in the previous PR, didn't notice it cannot be assigned like the other properties. Same story: in a mock of NanoDeviceBase you would want to specify the firmware version, to check whether it is the version required for the project.

## Types of changes
- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:
- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by frobijn** [comment]
@josesimoes The merge of this PR and of the previous one did not yet result in a new version of the nanoFramework.Tools.Debugger.Net package on [nuget.org](https://www.nuget.org/packages/nanoFramework.Tools.Debugger.Net/). Should I be more patient for the package to show up or was no new package created?

**Comment by josesimoes** [comment]
@frobijn as these where internal changes with no impact on usage, I did hold the nuget release waiting for more changes.
Let me know if you need a new version for your work and I'll fire the build.

**Comment by frobijn** [comment]
@josesimoes Yes please. I'm using the library and mocks in other repositories.

**Comment by josesimoes** [comment]
@frobijn done and published!

**Comment by frobijn** [comment]
@josesimoes Thanks!

**Pull request merged**
